# 테마 바꾸기
[theme]
base = "dark"

# Primary accent color.
primaryColor = "#94b3db"

# Background color of the app.
backgroundColor = "#9894db"

# Background color used for most interactive widgets.
secondaryBackgroundColor = "#bb94db"

# Color used for almost all text.
# textColor =
